<?php

/**
* Implements hook_theme
*/
function wembassy_theme($existing, $type, $theme, $path) {
  return [
    'wembassy_breakpoint_form' => [
      'render element' => 'form',
      'template' => 'wembassy-breakpoint-form'
    ],
    'wembassy_backend_template' => [
      'render element' => 'form',
      'template' => 'wembassy-backend-template'
    ],
    'wembassy_frontend_builder' => [
      'variables' => [
        'assets' => NULL,
        'plugins' => NULL,
        'pluginOpts' => NULL,
        'sectors' => NULL,
      ]
    ],
  ];
}

function wembassy_preprocess_page(&$vars) {

}

function wembassy_theme_suggestions_alter(array &$suggestions, array &$variables, $hook) {
  if ($hook == 'page') {
    $variables['page']['#attached']['drupalSettings']['wembassy']['siteBuilder']['template_suggestions'] = $suggestions;
  }

}
